/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // guideSidebar: [{ type: 'autogenerated', dirName: 'guide' }],
  changelogSidebar: [{ type: 'autogenerated', dirName: 'changelog' }],
  guideSidebar: [
    'guide/introduction', 'guide/installation', 'guide/contribution',
    {
      type: 'category',
      label: 'Documentation',
      items: [
        'guide/usage/projects', 'guide/usage/dashboard', 'guide/usage/variables',
        'guide/usage/import',
        {
          type: 'category',
          label: 'Export',
          link: { type: 'doc', id: 'guide/usage/export/index' },
          items: [
            'guide/usage/export/javascript',
            'guide/usage/export/php_laravel',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
